import { useEffect, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { createStudent } from '../api/students.js'
import { listClasses } from '../api/classes.js'
import { SCHOOL_LEVELS } from '../constants/schoolLevels.js'
import ClassSelect from '../components/ClassSelect.jsx'
import ErrorBanner from '../components/ErrorBanner.jsx'

const EMPTY_FORM = {
  firstName: '',
  lastName: '',
  studentNumber: '',
  schoolLevel: '',
  classId: '',
  educmasterNumber: '',
}

export default function AdminStudentCreatePage() {
  const navigate = useNavigate()
  const { t } = useTranslation()
  const [form, setForm] = useState(EMPTY_FORM)
  const [error, setError] = useState(null)
  const [saving, setSaving] = useState(false)
  const [classes, setClasses] = useState([])

  useEffect(() => {
    let cancelled = false
    listClasses()
      .then((data) => {
        if (!cancelled) setClasses(data)
      })
      .catch(() => {
        /* non-fatal: the class dropdown just stays empty */
      })
    return () => {
      cancelled = true
    }
  }, [])

  function updateField(field, value) {
    setForm((current) => ({ ...current, [field]: value }))
  }

  async function handleSubmit(event) {
    event.preventDefault()
    setError(null)

    if (!form.firstName.trim() || !form.lastName.trim()) {
      setError(t('students.errorNameRequired'))
      return
    }

    setSaving(true)
    try {
      await createStudent(form)
      navigate('/admin/students', {
        state: { message: t('students.created') },
      })
    } catch (err) {
      setError(err.message)
    } finally {
      setSaving(false)
    }
  }

  return (
    <section className="admin-page">
      <Link to="/admin/students" className="back-link">
        ← {t('students.title')}
      </Link>

      <div className="report-header">
        <div>
          <h2 className="page-title">{t('students.addStudent')}</h2>
          <p className="muted">{t('students.createSubtitle')}</p>
        </div>
      </div>

      {error && <ErrorBanner message={error} />}

      <form className="card admin-form" onSubmit={handleSubmit}>
        <label className="field">
          <span>{t('students.firstName')}</span>
          <input
            value={form.firstName}
            onChange={(event) => updateField('firstName', event.target.value)}
            disabled={saving}
            required
          />
        </label>

        <label className="field">
          <span>{t('students.lastName')}</span>
          <input
            value={form.lastName}
            onChange={(event) => updateField('lastName', event.target.value)}
            disabled={saving}
            required
          />
        </label>

        <label className="field">
          <span>{t('students.studentNumber')}</span>
          <input
            value={form.studentNumber}
            onChange={(event) => updateField('studentNumber', event.target.value)}
            disabled={saving}
            placeholder={t('students.autoGenerated')}
          />
        </label>

        <label className="field">
          <span>{t('students.schoolLevel')}</span>
          <select
            className="grade-input"
            value={form.schoolLevel}
            onChange={(event) => updateField('schoolLevel', event.target.value)}
            disabled={saving}
            style={{ width: '100%', textAlign: 'left' }}
          >
            <option value="">{t('common.notSet')}</option>
            {SCHOOL_LEVELS.map((level) => (
              <option key={level.value} value={level.value}>
                {level.label}
              </option>
            ))}
          </select>
        </label>

        <label className="field">
          <span>{t('students.classLabel')}</span>
          <ClassSelect
            classes={classes}
            value={form.classId}
            onChange={(value) => updateField('classId', value)}
            disabled={saving}
          />
        </label>

        <label className="field">
          <span>{t('students.educmaster')}</span>
          <input
            value={form.educmasterNumber}
            onChange={(event) => updateField('educmasterNumber', event.target.value)}
            disabled={saving}
            placeholder={t('students.educmasterPlaceholder')}
          />
        </label>

        <div className="grade-actions">
          <button type="submit" className="btn btn-primary" disabled={saving}>
            {saving ? t('students.creating') : t('students.create')}
          </button>
          <Link to="/admin/students" className="btn btn-ghost">
            {t('common.cancel')}
          </Link>
        </div>
      </form>
    </section>
  )
}
